# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bcb2213c94e38d59890392a610bb3022132b16ae1e35d51c83916e171a3cc255f5445b8dd0b8a6935553f8e488bd56b6d5320b87ea0e3965f4a8284796e84ea

test:
  secret_key_base: 166a8731de4b9a12449756efd9ebf82a8eec2ad28e32b28b03daa22de6c5d4c3fde97c33761a22042fcd0892e0f6c9b3bc05b8ba3df953d67ea462ff557e63c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
